esphome:
  name: y8
  friendly_name: y8

esp8266:
  board: d1

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "dB8zmymwLHKZJCtt6dKQV3N808Y7rbnnKMRXfeqxFWA="

ota:
  password: "105fd2e1d27692498100e396f1118809"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Yosh Muhaimin Psuap"
    password: "muhaimin"


web_server:
  port: 80
  local: true
  version: 2
  include_internal: false
  ota: true
  log: true
  css_url: ''
  js_url: https://oi.esphome.io/v2/www.js



captive_portal: {}
i2c:
- sda: 4
  scl: 5
  scan: true
  id: bus_a
  frequency: 50000.0
sensor:
- platform: ina3221
  address: 0x40
  channel_1:
    shunt_resistance: 0.1
    current:
      id: usb1a
      name: USB1 Ampere
      disabled_by_default: false
      force_update: true
      unit_of_measurement: A
      accuracy_decimals: 2
      device_class: current
      state_class: measurement
    power:
      id: usb1power
      name: USB1 Power
      disabled_by_default: false
      force_update: false
      unit_of_measurement: W
      accuracy_decimals: 2
      device_class: power
      state_class: measurement
    bus_voltage:
      id: usb1volt
      name: USB1 Volt
      disabled_by_default: false
      force_update: true
      unit_of_measurement: V
      accuracy_decimals: 2
      device_class: voltage
      state_class: measurement

  channel_2:
    shunt_resistance: 0.1
    current:
      id: usb2a
      name: USB2 A
      disabled_by_default: false
      force_update: true
      unit_of_measurement: A
      accuracy_decimals: 2
      device_class: current
      state_class: measurement
    power:
      id: usb2power
      name: USB2 Power
      disabled_by_default: false
      force_update: false
      unit_of_measurement: W
      accuracy_decimals: 2
      device_class: power
      state_class: measurement
    bus_voltage:
      id: usb2volt
      name: USB2 Volt
      disabled_by_default: false
      force_update: true
      unit_of_measurement: V
      accuracy_decimals: 2
      device_class: voltage
      state_class: measurement

  channel_3:
    shunt_resistance: 0.1
    current:
      id: psua
      name: PSU A
      disabled_by_default: false
      force_update: true
      unit_of_measurement: A
      accuracy_decimals: 2
      device_class: current
      state_class: measurement
    power:
      id: psupower
      name: PSU Power
      disabled_by_default: false
      force_update: false
      unit_of_measurement: W
      accuracy_decimals: 2
      device_class: power
      state_class: measurement
    bus_voltage:
      id: psuvolt
      name: PSU Volt
      disabled_by_default: false
      force_update: true
      unit_of_measurement: V
      accuracy_decimals: 2
      device_class: voltage
      state_class: measurement

  update_interval: 1ms
spi:
- clk_pin:
    number: 12
    mode:
      output: true

  mosi_pin:
    number: 14
    mode:
      output: true

display:
- platform: st7920
  rotation: 180
  width: 128
  height: 64
  cs_pin:
    number: 16
    inverted: true
    mode:
      output: true

  lambda: !lambda |-

    it.line(0, 0, 127, 0);
    it.line(0, 11, 98, 11);
    it.line(99, 10, 126, 10);
    it.line(99, 32, 126, 32);
    it.line(99, 42, 126, 42);
    it.line(0, 63, 127, 63);

    it.line(0, 64, 0, 0);
    it.line(127, 64, 127, 0);
    it.line(98, 64, 98, 0);

    it.print(2, 2, id(dot8x8), "PSUA SADEWO");
    
    
    it.printf(84, 14, id(symbola), "A");
    it.printf(2, 11, id(fusb1a), "%.3f", id(usb1a).state);

    it.printf(84, 40, id(symbola), "A");
    it.printf(2, 39, id(fusb1volt),"%.3f", id(psua).state);
    
    it.printf(102, 2, id(dot), "USB");
    it.printf(99, 10, id(seven), "%.2fV", id(usb2volt).state);
    it.printf(99, 20, id(seven), "%.2fA", id(usb2a).state);

    it.printf(102, 34, id(dot), "PSV");
    it.printf(99, 52, id(seven), "%.2fV", id(psuvolt).state);
    it.printf(99, 42, id(seven), "%.2fV", id(usb1volt).state);




  auto_clear_enabled: true
  update_interval: 31ms
font:
- file: "fonts/Lightdot-8x8.ttf"
  id: dot
  size: 7
- file: "fonts/Lightdot-8x8.ttf"
  id: dot8x8
  size: 8
- file: "fonts/SevenSegment.ttf"
  id: seven
  size: 12
- file: "fonts/psua.ttf"
  id: powers
  size: 20
- file: "fonts/usbfontbig.ttf"
  id: fusb1a
  size: 30
- file: "fonts/usbfontbig.ttf"
  id: fusb1volt
  size: 30
- file: "fonts/usbfontbig.ttf"
  id: symbola
  size: 28

output:
- platform: esp8266_pwm
  pin:
    number: 13
    inverted: true
  id: ledlcd
light:
  - platform: monochromatic
    output: ledlcd
    name: "lcd backlight"
  - platform: neopixelbus
    type: BGR
    variant: WS2811
    pin: GPIO0
    num_leds: 1
    name: "NeoPixel Light"
    effects:
      - strobe:
          name: Strobe Effect With Custom Values
          colors:
            - state: true
              brightness: 100%
              red: 100%
              green: 90%
              blue: 0%
              duration: 500ms
            - state: false
              duration: 250ms
            - state: true
              brightness: 100%
              red: 0%
              green: 100%
              blue: 0%
              duration: 500ms   
      - random:
          name: "My Slow Random Effect"
          transition_length: 30s
          update_interval: 30s
      - random:
          name: "My Fast Random Effect"
          transition_length: 4s
          update_interval: 5s 
      - random:
          name: Random Effect With Custom Values
          transition_length: 5s
          update_interval: 7s
      - pulse:
          name: "Fast Pulse"
          transition_length: 0.5s
          update_interval: 0.5s
          min_brightness: 0%
          max_brightness: 100%
      - pulse:
          name: "Slow Pulse"
          # transition_length: 1s      # defaults to 1s
          update_interval: 2s
      - flicker:
          name: Flicker Effect With Custom Values
          alpha: 95%
          intensity: 1.5%
      - addressable_rainbow:
          name: Rainbow Effect With Custom Values
          speed: 10
          width: 50
      - addressable_color_wipe:
          name: Color Wipe Effect With Custom Values
          colors:
            - red: 100%
              green: 100%
              blue: 100%
              num_leds: 1
            - red: 0%
              green: 0%
              blue: 0%
              num_leds: 1
          add_led_interval: 100ms
          reverse: false
      - addressable_scan:
          name: Scan Effect With Custom Values
          move_interval: 100ms
          scan_width: 1
      - addressable_twinkle:
          name: Twinkle Effect With Custom Values
          twinkle_probability: 5%
          progress_interval: 4ms
      - addressable_random_twinkle:
          name: Random Twinkle Effect With Custom Values
          twinkle_probability: 5%
          progress_interval: 32ms
      - addressable_fireworks:
          name: Fireworks Effect With Custom Values
          update_interval: 32ms
          spark_probability: 10%
          use_random_color: false
          fade_out_rate: 120
    
    restore_mode: ALWAYS_ON
    